/*
    carry_savings_analysis.c

    Diagnostic tool for the 512/1024-bit carry predictor.

    Goal:
      Show where the predictor is "saving" work compared with serial carry.

    It measures:
      - generated carries per word position
      - propagated carries per word position
      - carry chain lengths
      - how often each word receives an incoming carry

    Build:
      clang -O3 carry_savings_analysis.c -o carry_savings_analysis

    Run:
      ./carry_savings_analysis
*/

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#define TRIALS 1000000u
#define MAX_WORDS 32u

static uint64_t rng_state = 0x123456789abcdefULL;

static inline uint32_t xorshift32(void) {
    uint64_t x = rng_state;
    x ^= x << 13;
    x ^= x >> 7;
    x ^= x << 17;
    rng_state = x;
    return (uint32_t)(x >> 32) ^ (uint32_t)x;
}

typedef struct {
    uint64_t generated[MAX_WORDS];
    uint64_t propagated[MAX_WORDS];
    uint64_t incoming_carry[MAX_WORDS];
    uint64_t carry_out[MAX_WORDS];

    uint64_t total_generated;
    uint64_t total_propagated;
    uint64_t total_incoming;
    uint64_t total_carry_out;

    uint64_t chains;
    uint64_t total_chain_len;
    uint64_t max_chain;
} CarryStats;

static void clear_stats(CarryStats *s) {
    memset(s, 0, sizeof(*s));
}

static void analyze_one(const uint32_t *A, const uint32_t *B, uint32_t words, CarryStats *stats) {
    uint32_t carry = 0;
    uint32_t current_chain = 0;
    uint32_t in_chain = 0;

    for (uint32_t i = 0; i < words; i++) {
        uint32_t a = A[i];
        uint32_t b = B[i];

        uint32_t sum0 = a + b;

        uint32_t g = (sum0 < a) ? 1u : 0u;
        uint32_t p = (sum0 == 0xffffffffu) ? 1u : 0u;

        uint32_t carry_in = carry;
        uint32_t carry_out = g | (p & carry_in);

        if (g) {
            stats->generated[i]++;
            stats->total_generated++;
        }

        if (p) {
            stats->propagated[i]++;
            stats->total_propagated++;
        }

        if (carry_in) {
            stats->incoming_carry[i]++;
            stats->total_incoming++;
        }

        if (carry_out) {
            stats->carry_out[i]++;
            stats->total_carry_out++;
        }

        if (carry_out) {
            if (!in_chain) {
                stats->chains++;
                in_chain = 1;
                current_chain = 1;
            } else {
                current_chain++;
            }
        } else {
            if (in_chain) {
                stats->total_chain_len += current_chain;
                if (current_chain > stats->max_chain) stats->max_chain = current_chain;
            }
            in_chain = 0;
            current_chain = 0;
        }

        carry = carry_out;
    }

    if (in_chain) {
        stats->total_chain_len += current_chain;
        if (current_chain > stats->max_chain) stats->max_chain = current_chain;
    }
}

static void print_bar(double pct) {
    int width = 40;
    int filled = (int)((pct / 100.0) * width);
    if (filled > width) filled = width;

    for (int i = 0; i < filled; i++) putchar('#');
    for (int i = filled; i < width; i++) putchar('.');
}

static void run_width(uint32_t words, const char *label) {
    CarryStats stats;
    clear_stats(&stats);

    uint32_t A[MAX_WORDS];
    uint32_t B[MAX_WORDS];

    for (uint32_t t = 0; t < TRIALS; t++) {
        for (uint32_t i = 0; i < words; i++) {
            A[i] = xorshift32();
            B[i] = xorshift32();
        }

        analyze_one(A, B, words, &stats);
    }

    double avg_generated = (double)stats.total_generated / (double)TRIALS;
    double avg_propagated = (double)stats.total_propagated / (double)TRIALS;
    double avg_incoming = (double)stats.total_incoming / (double)TRIALS;
    double avg_carry_out = (double)stats.total_carry_out / (double)TRIALS;
    double avg_chain = stats.chains ? (double)stats.total_chain_len / (double)stats.chains : 0.0;

    printf("\n============================================================\n");
    printf("%s carry analysis\n", label);
    printf("words=%u trials=%u\n", words, TRIALS);
    printf("============================================================\n");

    printf("avg generated carries:      %.4f / %u words\n", avg_generated, words);
    printf("avg propagated words:       %.8f / %u words\n", avg_propagated, words);
    printf("avg incoming-carry words:   %.4f / %u words\n", avg_incoming, words);
    printf("avg carry-out words:        %.4f / %u words\n", avg_carry_out, words);
    printf("avg carry chain length:     %.4f\n", avg_chain);
    printf("max observed chain length:  %llu\n", (unsigned long long)stats.max_chain);

    printf("\nWhere carries are generated by word position:\n");
    for (uint32_t i = 0; i < words; i++) {
        double pct = 100.0 * (double)stats.generated[i] / (double)TRIALS;
        printf("word %02u generated %6.2f%% ", i, pct);
        print_bar(pct);
        printf("\n");
    }

    printf("\nWhere incoming carries arrive by word position:\n");
    for (uint32_t i = 0; i < words; i++) {
        double pct = 100.0 * (double)stats.incoming_carry[i] / (double)TRIALS;
        printf("word %02u incoming  %6.2f%% ", i, pct);
        print_bar(pct);
        printf("\n");
    }

    printf("\nWhere propagation condition appears, p = sum == 0xffffffff:\n");
    for (uint32_t i = 0; i < words; i++) {
        double pct = 100.0 * (double)stats.propagated[i] / (double)TRIALS;
        printf("word %02u propagate %8.6f%% ", i, pct);
        print_bar(pct);
        printf("\n");
    }

    printf("\nInterpretation:\n");
    printf("  Generated carries are common because random 32-bit word adds overflow about 50%% of the time.\n");
    printf("  True propagate words are rare for random data because sum == 0xffffffff is about 1 / 2^32.\n");
    printf("  The predictor does not remove generated carries.\n");
    printf("  It saves by separating local word sums from carry-state movement.\n");
}

int main(void) {
    printf("Carry Savings Analysis\n");

    run_width(16, "512-bit");
    run_width(32, "1024-bit");

    return 0;
}
